<?php


class TestCase extends Orchestra\Testbench\TestCase
{
    protected function getPackageProviders($app)
    {
        return [
            AppCoreProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {

    }

    protected function setUp(): void
    {
        print (1);
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
