<?php
namespace Socialhead\Core;
use \Socialhead\Core\Console\ScheduleCheckShops;

class AppCoreProvider extends \App\Providers\AppServiceProvider
{
    public function boot()
    {
        //run command
        if ($this->app->runningInConsole()) {
            //Loading command
            $this->commands([
                ScheduleCheckShops::class
            ]);
            // Publish views
            $this->publishes([
                __DIR__.'/../resources/views' => resource_path('views/vendor/socialhead/views'),
            ], 'views');
            $this->publishes([
                __DIR__.'/../resources/assets' => public_path('assets/socialhead'),
            ], 'assets');

            $this->publishes([
                __DIR__.'/../config/socialhead.php' => config_path('socialhead.php'),
            ], 'config');

            if (! class_exists('CreateShopsTable')) {
                $this->publishes([
                    __DIR__ . '/../database/migrations/create_shops_migration.php.stub' => database_path('migrations/' . date('Y_m_d_His', time()) . '_create_shops_table.php'),
                    // you can add any number of migrations here
                ], 'migrations');
            }
        }

        //loading migrations
        $this->loadMigrationsFrom(__DIR__.'/../database/migrations');

        // Loading router
        $this->loadRoutesFrom(__DIR__.'/../routes/web.php');

        //Loading view
        $this->loadViewsFrom(__DIR__.'/../resources/views', 'socialheadviews');


        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        $this->mergeConfigFrom(__DIR__.'/../config/socialhead.php', 'socialhead');
        $this->app->register(EventServiceProvider::class);
        parent::register(); // TODO: Change the autogenerated stub
    }
}
